"""initial

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-13 00:15:21.241345
"""
from alembic import op
import sqlalchemy as sa
import tandemista.db.types

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dropzones',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('payment_provider', sa.String(), nullable=True),
    sa.Column('storage_config', tandemista.db.types.JSONColumn(), nullable=False),
    sa.Column('enabled_variants', tandemista.db.types.JSONColumn(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('dropzone_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dropzone_id'], ['dropzones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loads',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('dropzone_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('takeoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dropzone_id'], ['dropzones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_sources',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('dropzone_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('config', tandemista.db.types.JSONColumn(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dropzone_id'], ['dropzones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('dropzone_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dropzone_id'], ['dropzones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('dropzone_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('owner_user_id', tandemista.db.types.GUID(), nullable=True),
    sa.Column('clock_offset_seconds', sa.Float(), nullable=False),
    sa.Column('fingerprints', tandemista.db.types.JSONColumn(), nullable=False),
    sa.Column('upload_source_id', tandemista.db.types.GUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dropzone_id'], ['dropzones.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upload_source_id'], ['upload_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tandem_jumps',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('dropzone_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('customer_id', tandemista.db.types.GUID(), nullable=True),
    sa.Column('load_id', tandemista.db.types.GUID(), nullable=True),
    sa.Column('instructor_user_id', tandemista.db.types.GUID(), nullable=True),
    sa.Column('outside_user_id', tandemista.db.types.GUID(), nullable=True),
    sa.Column('video_package', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['dropzone_id'], ['dropzones.id'], ),
    sa.ForeignKeyConstraint(['instructor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['outside_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jump_cuts',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('dropzone_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('jump_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('variant', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('edl', tandemista.db.types.JSONColumn(), nullable=False),
    sa.Column('proxy_location', sa.String(), nullable=True),
    sa.Column('render_location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dropzone_id'], ['dropzones.id'], ),
    sa.ForeignKeyConstraint(['jump_id'], ['tandem_jumps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jump_id', 'variant', name='uq_jumpcut_jump_variant')
    )
    op.create_table('media_files',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('dropzone_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('jump_id', tandemista.db.types.GUID(), nullable=True),
    sa.Column('device_id', tandemista.db.types.GUID(), nullable=True),
    sa.Column('upload_source_id', tandemista.db.types.GUID(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('locations', tandemista.db.types.JSONColumn(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('telemetry', tandemista.db.types.JSONColumn(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['dropzone_id'], ['dropzones.id'], ),
    sa.ForeignKeyConstraint(['jump_id'], ['tandem_jumps.id'], ),
    sa.ForeignKeyConstraint(['upload_source_id'], ['upload_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('dropzone_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('jump_id', tandemista.db.types.GUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dropzone_id'], ['dropzones.id'], ),
    sa.ForeignKeyConstraint(['jump_id'], ['tandem_jumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('media_files')
    op.drop_table('jump_cuts')
    op.drop_table('tandem_jumps')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('upload_sources')
    op.drop_table('loads')
    op.drop_table('customers')
    op.drop_table('dropzones')
    # ### end Alembic commands ###
